env: 
  VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
